# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e258b069df0c697035ac6182a9956263d9e9287094d446dc0e358fce6db7580da50e95f3bfa81b0176aeed41f194c03a219d7a94e431d21254501892d6388841

test:
  secret_key_base: a71113ff5629ad5656fa4df27bcc3e49a730c47fbf55f98209934b6d99abe631bb03acee61970126a2230a08da840e68ea804c6911a8cabdb6e554a769670779

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
